// Angular/HMI-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import * as _ from 'lodash';
import { WebsocketWrapperService } from './services/websocket-wrapper.service';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
    title = 'app';
    ws;
    clock;
    clicked = true;

    constructor (private webSocketService: WebsocketWrapperService) {
        this.ws = new WebSocket('ws://127.0.0.1:5678/');
    }

    ngOnInit() {
        this.webSocketService.init(this.ws);
    }

    updateWatch () {
        const date = new Date();
        const hour = date.getHours();
        const min = date.getMinutes();
        const day = date.getDate();
        const month = date.getMonth() + 1;
        const year = date.getFullYear();

        return this.addZeros([hour, min, day, month, year]);
    }

    addZeros (date) {
        for (let i = 0; i < date.length; i++) {
            if  (date[i] < 10) {
                date[i] = '0' + date[i];
            }
        }

        date = date[0] + ':' + date[1] + ' ' + date[2] + '/' + date[3] + '/' + date[4];
        return date;
    }
}

<div [ngClass]="{ 'menu-items-animated-down': clicked, 'menu-items-animated-up': !clicked }" >
    <nav class="nav-barr">
        <div class="menu-items" >
            <div routerLink="/" class="menu-item" (click)="clicked = true">
                <h2>
                    <img src="/assets/general/close.png">
                    <a>BACK</a>
                </h2>
            </div>
            <div routerLink="tuner" class="menu-item" (click)="clicked = false">
                <h2>
                    <img src="/assets/general/radio.png">
                    <a>TUNER</a>
                </h2>
            </div>

            <div routerLink="media" class="menu-item" (click)="clicked = false">
                <h2>
                    <img src="/assets/general/media.png">
                    <a>MEDIA</a>
                </h2>
            </div>

            <div routerLink="navigation" class="menu-item" (click)="clicked = false">
                <h2>
                    <img src="/assets/general/navigation.png">
                    <a>NAVI</a>
                </h2>
            </div>

            <div routerLink="settings" class="menu-item" (click)="clicked = false">
                <h2>
                    <img src="/assets/general/settings.png">
                    <a>SETTINGS</a>
                </h2>
            </div>  
            <hr>
        </div>
        <div class="date-container">
            <h2>
              <div class="date">{{ updateWatch() }}</div>
          </h2>
        </div>
    </nav>
    <br>
    
</div>
<app-home></app-home>

// React/HMI-app/src/App.js
import React, { Component } from 'react';
import * as _ from 'lodash'
// import logo from './logo.svg';
import './App.css';
import { Link } from 'react-router-dom';
import { withRouter } from 'react-router-dom';
import { Websocket } from './websocket/websocket.service';
import { MediaService } from './media//media.service';

const WSContext = React.createContext({});

class App extends Component {
    constructor(props) {
        super(props);
        Websocket.initWS();
        this.ws = Websocket.getWS();
        this.mediaService = new MediaService();

        this.props.location.mediaService = this.mediaService;
        
        this.props.history.listen(this.locationWatcher.bind(this));
        this.menuHidden = false;
        console.warn('!@!@##', this.ws);
        this.media = { 
            pathname: '/media', 
            props: {
                mediaservice: this.mediaService
            }
        };
    }

    locationWatcher (location, action) {
        this.toggleMenu(location);
    }

    toggleMenu (location) {
        if (location && (location.pathname === '/' || location.pathname === '')) {
            this.menuHidden = false;
        } else {
            this.menuHidden = true;
        }
    }
    
    render() {
        return (
            <div className={ this.menuHidden ? 'menu-items-animated-up' : 'menu-items-animated-down' }>
                <nav className='nav-barr'>
                    <div className='menu-items' >
                        <Link to='/' className='menu-item'>
                            <h2>
                                <img src={require('./assets/general/close.png')} />
                                <span>BACK</span>
                            </h2>
                        </Link>
                        <Link to='/tuner' ws={{ws: this.ws}} className='menu-item'>
                            <h2>
                                <img src={require('./assets/general/radio.png')} />
                                <span>TUNER</span>
                            </h2>
                        </Link>

                        <Link to='/media' className='menu-item' >
                            <h2>
                                <img src={require('./assets/general/media.png')} />
                                <span>MEDIA</span>
                            </h2>
                        </Link>

                        <Link to='/navigation' className='menu-item'>
                            <h2>
                                <img src={require('./assets/general/navigation.png')} />
                                <span>NAVI</span>
                            </h2>
                        </Link>

                        <Link to='/settings' className='menu-item'>
                            <h2>
                                <img src={require('./assets/general/settings.png')} />
                                <span>SETTINGS</span>
                            </h2>
                        </Link>
                        <hr />
                    </div>
                    <div className='date-container'>
                        <h2>
                          <div className='date'>13:59</div>
                      </h2>
                    </div>
                </nav>
                <br />
            </div>
        );
    }
}

export default withRouter(App);
