// React/HMI-app/src/settings/others-settings/others-settings.component.js
import React from 'react';
import './others-settings.component.css';

const OTHERS = {
	units: {
		0: 'km',
		1: 'mil',
		selected: 0
	},
	memory: 38
};

export class OthersSettings extends React.Component {
	constructor(props) {
		super(props);


		this.state = {
			OTHERS: OTHERS
		};
	}

	changeValue(key, value, event) {
		event.preventDefault();
		event.stopPropagation();

		let others = this.state.OTHERS;
		switch (key) {
			case 'units':
				// send for feneral
				others[key].selected = value;
				console.warn(key.toUpperCase() + ' units changed: ');
				break;
			default:
				console.warn('Unknown key ', key);
				return;
		}


		this.setState({ OTHERS: others }); // to update value!!
	}

	render() {
		return (
			<div className="others-settings">
				<div className="units">
					<h3>Units:</h3>
					<div onClick={this.changeValue.bind(this, 'units', 0)}>
						<input
							type="radio"
							name="units"
							checked={this.state.OTHERS.units.selected === 0}
							onChange={() => {}}/>
						<label>Kilometres</label>
					</div>
					<div onClick={this.changeValue.bind(this, 'units', 1)}>
						<input
							type="radio"
							name="units"
							checked={this.state.OTHERS.units.selected === 1}
							onChange={() => {}}/>
						<label>Miles</label>
					</div>
				</div>
				<div>
					<h3>Memory usage (%):</h3>
					<button disabled={true}>-</button>
					<progress value={this.state.OTHERS['memory']} max="100"></progress>
					<button disabled={true}>+</button>
				</div>
			</div>
		);
	}
}

// Angular/HMI-app/src/app/settings/others-settings/others-settings.component.ts
import { Component, OnInit } from '@angular/core';

import { ConstantsService } from '../../consts/constants.service';

@Component({
	selector: 'app-others-settings',
	templateUrl: './others-settings.component.html',
	styleUrls: ['./others-settings.component.css']
})
export class OthersSettingsComponent implements OnInit {

	OTHERS;
	constructor(private constantsService: ConstantsService) {
		this.OTHERS = this.constantsService.OTHERS_SETTINGS;
	}

	ngOnInit() {
	}

	changeValue (event, key, value) {
		if (event.target.closest('app-others-settings') !== null) {
			event.preventDefault();
			event.stopPropagation();
		} 
		 
		switch (key) {
			case 'units':
				// send for feneral
				this.OTHERS[key].selected = value;
				console.warn(key.toUpperCase() + ' units changed: ' + this.OTHERS[key].selected); 
				break;
			default:
				console.warn('Unknown key ', key);
				return;				
		}
	} 
}

<div class="others-settings">
	<div class="units">
		<h3>Units:</h3>
		<div (click)="changeValue($event, 'units', 0)">
			<input type="radio" name="units" [checked]="OTHERS.units.selected === 0">
			<label>Kilometres</label>
		</div>
		<div (click)="changeValue($event, 'units', 1)">
			<input type="radio" name="units" [checked]="OTHERS.units.selected === 1">
			<label>Miles</label>
		</div>
	</div>
	<div>
		<h3>Memory usage (%):</h3>
		<button [disabled]="true">-</button>
		<progress value="{{ OTHERS['memory'] }}" max="100"></progress>
		<button [disabled]="true">+</button>
	</div>
	<!-- <div>
		<h3>Balance:</h3>
		<button (click)="changeValue($event, 'balance', -1)">Left</button>
		<progress value="{{ OTHERS['balance'] }}" min="-50" max="50"></progress>
		<button (click)="changeValue($event, 'balance', 1)">Right</button>
	</div>
	<div>
		<h3>Fader:</h3>
		<button (click)="changeValue($event, 'fader', -1)">Front</button>
		<progress value="{{ OTHERS['fader'] }}" min="-50" max="50"></progress>
		<button (click)="changeValue($event, 'fader', 1)">Rear</button>
	</div>
	 -->	
</div>
