// React/HMI-app/src/settings/settings.component.js
import React from 'react';
import './settings.component.css';
import { DisplaySettings } from './display-settings/display-settings.component';
import { AudioSettings } from './audio-settings/audio-settings.component';
import { OthersSettings } from './others-settings/others-settings.component';

const _settingsArray = [
	{
		id: 1,
		name: 'Display',
		component: <DisplaySettings />,
		icon: '/assets/settings/display-settings.png'
	},
	{
		id: 2,
		name: 'Audio',
		component: <AudioSettings />,
		icon: '/assets/settings/audio-settings.png'
	},
	{
		id: 3,
		name: 'Others',
		component: <OthersSettings />,
		icon: '/assets/settings/others-settings.png'
	}
];

// function Display (props) {
// 	return <DisplaySettings />
// }

// function Audio (props) {
// 	return <AudioSettings />
// }

// function Others (props) {
// 	return <OthersSettings />
// }

export class Settings extends React.Component {
	constructor (props) {
		super(props);
		this.selectedItem = {};
		this.item = {};
		this.createList();
		this.state = {
			selectedItem: this.selectedItem
		};
	}

	createList () {
		let ul = [];
		let li = [];

		for (var i=0; i<_settingsArray.length; i++) {
			let item = _settingsArray[i];

			li.push(
				<li className="list-item" onClick={this.onSelect.bind(this, item)}>
					<img src={item.icon} className="icon" />
					<span>{ item.name }</span>
					<div className="sub-settings">
						<div className={(this.selectedItem.name === item.name && item.id === i+1) ? 'show-module' : 'hide-module'}>
							{item.component}
						</div>
					</div>
				</li>
			);
		}

		ul.push(<ul>{li}</ul>);
		return ul;
	}

	openDisplaySettings() {
		this.props.history.push('/settings/display-settings');
	}

	openAudioSettings() {
		this.props.history.push('/settings/audio-settings');
	}

	openOthersSettings() {
		this.props.history.push('/settings/others-settings');
	}

	onSelect (item, event) {
		// console.log ('%%%%%%%%', event.target.closest('app-audio-settings') ) 
		// if ((event.target.closest('app-audio-settings') !== null) ||
		// 		(event.target.closest('app-display-settings') !== null) ||
		// 		(event.target.closest('app-others-settings') !== null)) {
		// 	event.preventDefault();
		// 	event.stopPropagation();
		// 	return;
		// } 
		
		if (!this.selectedItem || this.selectedItem !== item) {
			this.selectedItem = item;
		} else {
			this.selectedItem = {};
		}
		// console.warn ('@@!! selectedItem', item); 
		this.createList();
		this.setState({selectedItem: this.selectedItem}); // to update value!!
	} 

				// <ul>
				// 	<li className="list-item" onClick={this.onSelect.bind(this, this.item)}>
				// 		<img src={this.item.icon} className="icon" />
				// 		<span>{ this.item.name }</span>
				// 		<div className="sub-settings">
				// 			<Display />
				// 		</div>
				// 	</li>
				// </ul>

	render() {
		return (
			<div className="settings">
				{ this.createList() }
			</div>
		);
	}
}

// Angular/HMI-app/src/app/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
	selector: 'app-settings',
	templateUrl: './settings.component.html',
	styleUrls: ['./settings.component.css']
})
export class SettingsComponent implements OnInit {
	selectedItem;

	constructor(private router: Router) { 
		this._settings = this.settings;
	}

	public get settings() : Object[] {
		return this._settingsArray;
	}

	ngOnInit() {
	}

	onSelect (event, item) {
		// console.log ('%%%%%%%%', event.target.closest('app-audio-settings') ) 
		if ((event.target.closest('app-audio-settings') !== null) ||
				(event.target.closest('app-display-settings') !== null) ||
				(event.target.closest('app-others-settings') !== null)) {
			event.preventDefault();
			event.stopPropagation();
			return;
		} 
		
		if (!this.selectedItem || this.selectedItem !== item) {
			this.selectedItem = item;
		} else {
			this.selectedItem = null;
		}
		// console.warn ('@@!! selectedItem', item); 
	} 

	_settingsArray = [
		{
			id: 1,
			name: 'Display',
			icon: '/assets/settings/display-settings.png'
		},
		{
			id: 2,
			name: 'Audio',
			icon: '/assets/settings/audio-settings.png'
		},
		{
			id: 3,
			name: 'Others',
			icon: '/assets/settings/others-settings.png'
		}
	];
}


<div class="settings">
	<ul>
		<li class="list-item" *ngFor="let item of settings" (click)="onSelect($event, item)">
			<img [src]="item.icon" class="icon">
			<span>{{ item.name }}</span>
			<div class="sub-settings">
				<app-display-settings *ngIf="selectedItem?.name === 'Display' && item?.id === 1"></app-display-settings>
				<app-audio-settings *ngIf="selectedItem?.name === 'Audio' && item?.id === 2"></app-audio-settings>
				<app-others-settings *ngIf="selectedItem?.name === 'Others' && item?.id === 3"></app-others-settings>
			</div>
		</li>
	</ul>
</div>
