// Angular/HMI-app/src/app/UI/controls/controls.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
    selector: 'app-controls',
    templateUrl: './controls.component.html',
    styleUrls: ['./controls.component.css']
})
export class ControlsComponent implements OnInit {

    @Output() previous: EventEmitter<any> = new EventEmitter<any>();
    @Output() next: EventEmitter<any> = new EventEmitter<any>();
    @Output() openList: EventEmitter<any> = new EventEmitter<any>();

    constructor() { }

    ngOnInit() {
    }

    onPrev() {
        this.previous.emit();
    }

    onNext() {
        this.next.emit();
    }

    onOpenList() {
        this.openList.emit();
    }
}

<div class="controls">
    <button name="prev" (click)="onPrev()"></button>
    <button class="list-button" (click)="onOpenList()">LIST</button>
    <button name="next" (click)="onNext()" style="transform: rotateY(180deg);"></button>
</div>

// React/HMI-app/src/UI/Controls.js
import React from 'react';
import './Controls.css';

const controls = (props) => {
    return (
        <div className="controls">
            <button name="prev" onClick={props.prev}></button>
            <button className="list-button" onClick={props.openList}>LIST</button>
            <button name="next" onClick={props.next} style= { {transform: 'rotateY(180deg)' } }></button>
        </div>
    )
}

export default controls;
