// Angular/HMI-app/src/app/UI/source-selector/source-selector.component.ts
import { Component, OnInit, Output, EventEmitter, Input } from '@angular/core';

@Component({
  selector: 'app-source-selector',
  templateUrl: './source-selector.component.html',
  styleUrls: ['./source-selector.component.css']
})
export class SourceSelectorComponent implements OnInit {

  @Output() selectOption: EventEmitter<any> = new EventEmitter<any>();
  @Input() component: string;
  @Input() currentSource: Object[];

  constructor() { }

  ngOnInit() {
    console.log('@SS', this.component);
  }

  selectSource(source) {
    this.selectOption.emit(source);
  }

}

<div *ngIf="component === 'media'" class='source-selector'>
    <div (click)="selectSource('hdd')" [ngClass]="{'source-item' : true, 'active': (currentSource && currentSource.mediaID === 'hdd') }">
        <img class='source-icon' [src]="'assets/media/hdd.png'" alt='' />
        <span class='source-label'>HDD</span>
    </div>
    <div (click)="selectSource('usb')" [ngClass]="{'source-item': true, 'active': (currentSource && currentSource.mediaID === 'usb')}">
        <img class='source-icon' [src]="'assets/media/usb.png'" alt="" />
        <span class='source-label'>USB</span>
    </div>
    <div (click)="selectSource(e, 'bt')" [ngClass]="{'source-item': true, 'active': (currentSource && currentSource.mediaID === 'bt')}">
        <img class='source-icon' [src]="'assets/media/bt.png'" alt='' />
        <span class='source-label'>BT</span>
    </div>
    <hr />
</div>
);

<div *ngIf="component === 'tuner'" class='source-selector'>
    <div [ngClass]="{'source-item': true, 'active': (currentSource && currentSource.band==='fm')}" (click)="selectSource('fm')">
        <img class='source-icon' [src]="'assets/tuner/antena.png'" alt='' />
        <span class='source-label'>FM</span>
    </div>
    <div class="{'source-item': true, 'active': (currentSource && currentSource.band==='am')}" (click)="selectSource('am')">
        <img class='source-icon' [src]="'../assets/tuner/antena.png'" alt='' />
        <span class='source-label'>AM</span>
    </div>
    <hr />
</div>

// React/HMI-app/src/UI/SourceSelector.js
import React from 'react';

import './SourceSelector.css';

const sourceSelector = (props) => {
    console.log('SELECTOR', props);
    let selector = (
        <div className='source-selector'>
            <div onClick={(e) => props.selectSource(e, 'hdd')}
                className={'source-item' + (props.currentSource && props.currentSource.mediaID === 'hdd' ? ' active' : '')}>
                <img className='source-icon' src={require('../assets/media/hdd.png')} alt='' />
                <span className='source-label'>HDD</span>
            </div>
            <div onClick={(e) => props.selectSource(e, 'usb')}
                className={'source-item' + (props.currentSource && props.currentSource.mediaID === 'usb' ? ' active' : '')}>
                <img className='source-icon' src={require('../assets/media/usb.png')} alt='' />
                <span className='source-label'>USB</span>
            </div>
            <div onClick={(e) => props.selectSource(e, 'bt')}
                className={'source-item' + (props.currentSource && props.currentSource.mediaID === 'bt' ? ' active' : '')}>
                <img className='source-icon' src={require('../assets/media/bt.png')} alt='' />
                <span className='source-label'>BT</span>
            </div>
            <hr />
        </div>
    );
    if (props.match.path === '/tuner') {
        console.log('selector tuner', props, props.currentStation.band === 'fm' ? 'active' : 'aa');
        selector = (
            <div className='source-selector'>
                <div className={'source-item' + (props.currentStation.band === 'fm' ? ' active' : '')}
                    onClick={(e) => props.activateBand(e, 'fm')}>
                    <img className='source-icon' src={require('../assets/tuner/antena.png')} alt='' />
                    <span className='source-label'>FM</span>
                </div>
                <div className={'source-item' + (props.currentStation.band === 'am' ? ' active' : '')}
                    onClick={(e) => props.activateBand(e, 'am')}>
                    <img className='source-icon' src={require('../assets/tuner/antena.png')} alt='' />
                    <span className='source-label'>AM</span>
                </div>
                <hr />
            </div>

        )
    }
    return (<div>{selector}</div>);
}

export default sourceSelector;
