// React/HMI-app/src/navigation/EnterAddress.js
import React from 'react';
import Spinner from '../UI/Spinner';

const enterAddress = (props) => {

    let addressForm = (

        <form>
            <label>Country:
                <input type="text" name="country" placeholder="Enter country name" onChange={(e) => props.onChange(e, 'country')} />
            </label>
            <label>ZIP Code:
                <input type="number" disabled={!props.address.country} name="zipCode" placeholder="Enter ZIP code" onChange={(e) => props.onChange(e, 'zipCode')} />
            </label>
            <label>City:
                <input type="text" disabled={!props.address.zipCode} name="city" placeholder="Enter city name" onChange={(e) => props.onChange(e, 'city')} />
            </label>
            <label>Street:
                <input type="text" disabled={!props.address.city} name="street" placeholder="Enter street" onChange={(e) => props.onChange(e, 'street')} />
            </label>
            <label>Number:
                <input type="text" disabled={!props.address.street} name="number" placeholder="Enter house number" onChange={(e) => props.onChange(e, 'number')} />
            </label>
            <span className="span-enter-address">
                <button className="button-enter-address" 
                    onClick={(e) => props.onCancel(e)}>Cancel
                </button>
                <button className="button-enter-address" 
                    disabled={!(props.address.country || props.address.zipCode)} 
                    onClick={(e) => props.onSubmit(e)}>Confirm
                </button>
            </span>
        </form>
    );

    if (props.loading) {
        addressForm = <Spinner />;
    }

    return (
        <div className="enter-address">{addressForm}</div>
    );
}

export default enterAddress;

// Angular/HMI-app/src/app/navigation/_partials/enter-address/enter-address.component.ts
import { Component, OnInit, Output, EventEmitter, Input } from '@angular/core';

@Component({
    selector: 'app-enter-address',
    templateUrl: './enter-address.component.html',
    styleUrls: ['./enter-address.component.css']
})
export class EnterAddressComponent implements OnInit {

    @Input() address: Object;
    @Output() public buttonClick: EventEmitter<any> = new EventEmitter<any>();

    constructor() {
        this.address = {
        };
    }

    onChange = (ev, data) => {
        // ev.preventDefault();
        this.address = {
            ...this.address,
            [data]: ev
        };

        console.log('Enter address', this.address);
    }

    onSubmit = (ev, data) => {
        ev.preventDefault();

        console.log('on onAddressSubmit', data);
        this.buttonClick.emit({ event: ev, type: 'submit', address: this.address });
    }

    onCancel = (ev, data) => {
        ev.preventDefault();

        console.log('onCancel', data);
        this.buttonClick.emit({ event: ev, type: 'cancel' });
    }

    ngOnInit() {
    }

}

<div class="enter-address">
    <form #f="ngForm">
        <label>Country:
            <input type="text" 
                name="country" 
                placeholder="Enter country name" 
                ngModel #country="ngModel"
                (ngModelChange)="onChange($event, 'country' )" />
        </label>
        <label>ZIP Code:
            <input type="number" 
                [disabled]="!address.country" 
                name="zipCode" 
                placeholder="Enter ZIP code" 
                ngModel #zipCode="ngModel"
                (ngModelChange)="onChange($event, 'zipCode' )" />
        </label>
        <label>City:
            <input type="text" 
                [disabled]="!address.zipCode" 
                name="city" 
                placeholder="Enter city name" 
                ngModel #city="ngModel"
                (ngModelChange)="onChange($event, 'city' )" />
        </label>
        <label>Street:
            <input type="text" 
                [disabled]="!address.city" 
                name="street" 
                placeholder="Enter street" 
                ngModel #street="ngModel"
                (ngModelChange)="onChange($event, 'street' )" />
        </label>
        <label>Number:
            <input type="text" 
                [disabled]="!address.street" 
                name="number" 
                placeholder="Enter house number" 
                ngModel #number="ngModel"
                (ngModelChange)="onChange($event, 'number')" />
        </label>
        <span class="span-enter-address">
            <button class="button-enter-address" (click)="onCancel($event, 'cancel')">Cancel
            </button>
            <button class="button-enter-address" 
                [disabled]="!(address.country || address.zipCode)" 
                (click)="onSubmit($event, 'submit')">Confirm
            </button>
        </span>
    </form>
</div>
