// React/HMI-app/src/tuner/Tuner.js
import React from 'react';
import { connect } from 'react-redux';

import './Tuner.css';

import * as Actions from '../actions/actions';
import Controls from '../UI/Controls';
import Title from '../UI/Title';
import ProgressBar from '../UI/ProgressBar';
import Spinner from '../UI/Spinner';
import SourceSelector from '../UI/SourceSelector';
import CoverArt from '../UI/CoverArt';

class Tuner extends React.Component {
	constructor(props) {
		super(props);

		this.band = 'fm';
		// this.currentStationFM = {
		// 	fraquence: 88, // 87,5–108
		// 	name: 'Open.fm',
		// 	isFavorite: true,
		// 	band: 'fm'
		// }

		// this.currentStationAM = {
		// 	fraquence: 301, // 300–3000 kHz
		// 	name: 'Radio AMmm',
		// 	isFavorite: true,
		// 	band: 'am'
		// }
	
		this.state = {
			...this.state
		}
	}

	activateBand (ev, band) {
		if (band === this.props.currentStation.band) {
			return;
		}

		this.props.WS.send(JSON.stringify({ cmd: 'reqChangeBand', band: band }));
		// this.setState({ currentStation: null });
		this.props.setCurrentStation(null);
	}

	prevStation() {
		console.warn('@@ prevStation');
	}

	nextStation() {
		console.warn('@@ nextStation');
	}

	openList = () => {
		this.props.history.push('/tuner/list');
		this.props.WS.send(JSON.stringify({ cmd: 'reqTunerListItems', band: this.band }));
		console.warn('@@@ openList');
	}

	getProgressLabel = () => {
		let label = '';

		if (this.props.currentStation.band === 'am') {
			label = this.props.currentStation.fraquence + 'MHz';
		} else {
			label = this.props.currentStation.fraquence + 'kHz';
		}

		return label;
	}
	
	getActiveStation = () => {
		console.log('@@@!! ', this.props);
	}

	componentWillReceiveProps(data) {
	}

	componentDidMount() {
		this.getActiveStation();
		if (!this.props.currentStation) {
			this.props.WS.send(JSON.stringify({ cmd: 'reqCurrentStation' }));
		}
	}

	render() {
		let tuner = <Spinner />;

		if (this.props.currentStation) {
			tuner = (
				<div className="tuner-container">
					<SourceSelector activateBand={this.activateBand.bind(this)} currentStation={this.props.currentStation} match={this.props.match} />
					<Title
						name={this.props.currentStation.name}
						isFavorite={this.props.currentStation.isFavorite} />
					<ProgressBar
						value={this.props.currentStation.fraquence}
						max={this.props.currentStation.band === 'fm' ? 108 : 3000}
						min={this.props.currentStation.band === 'fm' ? 87.5 : 300}
						progressLabel={this.getProgressLabel()} />
					<Controls prev={this.prevStation} next={this.nextStation} openList={this.openList} />
					<CoverArt image={require('../assets/media/coverart.png')}/>
				</div>);
		}

		return (<div>{tuner}</div>);
	}
}


const mapStateToProps = state => {
    return {
		WS: state.webSocket,
		currentStation: state.currentStation
    };
}

const mapDispatchToState = dispatch => {
	return {
		setCurrentStation	: station => dispatch(Actions.setCurrentStation(station))
	}
}

export default connect(mapStateToProps, mapDispatchToState)(Tuner);

// Angular/HMI-app/src/app/tuner/tuner.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { TunerService } from '../services/tuner.service';
import { WebsocketWrapperService } from '../services/websocket-wrapper.service';

@Component({
    selector: 'app-tuner',
    templateUrl: './tuner.component.html',
    styleUrls: ['./tuner.component.css']
})
export class TunerComponent implements OnInit {

    constructor(private router: Router,
        private WS: WebsocketWrapperService) { }

    currentStation;
    currentStationAM;
    currentStationFM;
    band = 'fm';

    ngOnInit() {
        this.currentStationFM = {
            fraquence: 101.1, // 87,5–108
            name: 'Open.fm',
            isFavorite: true,
            band: 'fm'
        };

        this.currentStationAM = {
            fraquence: 554, // 300–3000 kHz
            name: 'Radio AMmm',
            isFavorite: true,
            band: 'am'
        };
        this.currentStation = this.currentStationFM;
    }

    activateBand(band) {
        if (band === 'am') {
            this.currentStation = this.currentStationAM;
        } else if (band === 'fm') {
            this.currentStation = this.currentStationFM;
        }
    }

    openList() {
        this.WS.send(JSON.stringify({ cmd: 'reqTunerListItems', band: this.band }));
        this.router.navigate(['tuner', 'list']);
    }

    nextStation(event) {
        console.log('[tuner.component] nextStation', event);
    }

    prevStation() {
        console.log('[tuner.component] prevStation');
    }
}

<div>
	<app-source-selector (selectOption)="activateBand($event)" [component]="'tuner'" [currentSource]="currentStation"></app-source-selector>
	<div class="station-title">
		<span class="fav-ico-container">
			<img *ngIf="currentStation?.isFavorite" class="fav-ico" src="assets/tuner/favorite_icon.png">
		</span>
		<span>
			{{ currentStation.name }}
		</span>
	</div>
	<div class="station-info">
		<div>
			<progress *ngIf="currentStation.band === 'fm'" value="{{ currentStation.fraquence }}" max="3000" min="300"></progress>
			<progress *ngIf="currentStation.band === 'am'" value="{{ currentStation.fraquence }}" max="108" min="87.5"></progress>
		</div>
		<div class="fraquence-info">
			<span *ngIf="currentStation.band === 'fm'" class="station-fraquence">{{ currentStation.fraquence }}MHz</span>
			<span *ngIf="currentStation.band === 'am'" class="station-fraquence">{{ currentStation.fraquence }}kHz</span>
		</div>
	</div>
	<app-controls (previous)="prevStation($event)" (next)="nextStation($event)" (openList)="openList($event)"></app-controls>
	<app-coverart></app-coverart>
</div>
