// React/HMI-app/src/tuner/tuner.component.js
import React from 'react';
import './tuner.component.css';
import { withRouter } from 'react-router-dom';
import { Websocket } from '../websocket/websocket.service';

export class Tuner extends React.Component {
	constructor(props) {
		super(props);

		this.band = 'fm';
		this.currentStationFM = {
	  		fraquence: 101.1, // 87,5–108
	  		name: 'Open.fm',
	  		isFavorite: true,
	  		band: 'fm'
	  	}

	  	this.currentStationAM = {
	  		fraquence: 554, // 300–3000 kHz
	  		name: 'Radio AMmm',
	  		isFavorite: true,
	  		band: 'am'
	  	}
	  	this.currentStation = this.currentStationFM;
	}


	activateBand (band) {
		if (band === 'am') {
		  	this.currentStation = this.currentStationAM;
	  	} else if (band === 'fm') {
	  		this.currentStation = this.currentStationFM;
	  	} 
	}

	prevStation () {
		console.warn('@@ prevStation');
	}

	nextStation () {
		console.warn('@@ nextStation');
	}

	openList () {
		this.props.history.push('/tuner/list');
		Websocket.send(JSON.stringify({ cmd: 'reqTunerListItems', band: this.band }));
		console.warn('@@@ openList');
	}

	render() {
		return (
			<div className="tuner-container">
				<div className="station-title">
					<span className="fav-ico-container">
						<img className="fav-ico" src={require('../assets/tuner/favorite_icon.png')} />
					</span>
					<span>
						{ this.currentStation.name }
					</span>
				</div>
				<div className="station-info">
					<div>
						{ this.currentStation.band === 'am' && <progress value={ this.currentStation.fraquence } max="108" min="87.5"></progress> }
						{ this.currentStation.band === 'fm' && <progress value={ this.currentStation.fraquence } max="3000" min="300"></progress> }
					</div>
					<div className="fraquence-info">
						<span className="station-fraquence">{ this.currentStation.fraquence }kHz</span>
					</div>
				</div>
				<div className="controls">
					<button name="prev" onClick={this.prevStation.bind(this)}></button>
					<button className="list-button" onClick={this.openList.bind(this)}>LIST</button>
					<button name="next"  onClick={this.nextStation.bind(this)} style={ {transform: 'rotateY(180deg)' } }></button>
				</div>
				<div className="band">
					<div className={ this.currentStation.band === 'fm' ? 'active' : '' } 
						onClick={this.activateBand.bind(this, 'fm')}>FM</div>
					<div className={ this.currentStation.band === 'am' ? 'active' : '' }
						onClick={this.activateBand.bind(this, 'am')}>AM</div>
				</div>
			</div>
		);
	}
}

// Angular/HMI-app/src/app/tuner/tuner.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { TunerService } from '../services/tuner.service';
import { WebsocketWrapperService } from '../services/websocket-wrapper.service';

@Component({
    selector: 'app-tuner',
    templateUrl: './tuner.component.html',
    styleUrls: ['./tuner.component.css']
})
export class TunerComponent implements OnInit {

    constructor(private router: Router,
        private WS: WebsocketWrapperService) { }

    currentStation;
    currentStationAM;
    currentStationFM;
    band = 'fm';

    ngOnInit() {
        this.currentStationFM = {
            fraquence: 101.1, // 87,5–108
            name: 'Open.fm',
            isFavorite: true,
            band: 'fm'
        };

        this.currentStationAM = {
            fraquence: 554, // 300–3000 kHz
            name: 'Radio AMmm',
            isFavorite: true,
            band: 'am'
        };
        this.currentStation = this.currentStationFM;
    }

    activateBand(band) {
        if (band === 'am') {
            this.currentStation = this.currentStationAM;
        } else if (band === 'fm') {
            this.currentStation = this.currentStationFM;
        }
    }

    openList() {
        this.WS.send(JSON.stringify({ cmd: 'reqTunerListItems', band: this.band }));
        this.router.navigate(['tuner', 'list']);
    }

}

<div>
	<div class="station-title">
		<span class="fav-ico-container">
			<img *ngIf="currentStation?.isFavorite" class="fav-ico" src="assets/tuner/favorite_icon.png">
		</span>
		<span>
			{{ currentStation.name }}
		</span>
	</div>
	<div class="station-info">
		<div>
			<progress *ngIf="currentStation.band === 'fm'" value="{{ currentStation.fraquence }}" max="3000" min="300"></progress>
			<progress *ngIf="currentStation.band === 'am'" value="{{ currentStation.fraquence }}" max="108" min="87.5"></progress>
		</div>
		<div class="fraquence-info">
			<span *ngIf="currentStation.band === 'fm'" class="station-fraquence">{{ currentStation.fraquence }}MHz</span>
			<span *ngIf="currentStation.band === 'am'" class="station-fraquence">{{ currentStation.fraquence }}kHz</span>
		</div>
	</div>
	<div class="controls">
		<button name="prev" (click)="prevStation()"></button>
		<button class="list-button" (click)="openList()">LIST</button>
		<button name="next"  (click)="nextStation()" style="transform: rotateY(180deg);"></button>
	</div>
	<div class="band">
		<div [ngClass]="{ 'active': currentStation.band === 'fm' }" (click)="activateBand('fm')">FM</div>
		<div [ngClass]="{ 'active': currentStation.band === 'am' }" (click)="activateBand('am')">AM</div>
	</div>
</div>
