// React/HMI-app/src/tuner/list/tuner.list.component.js
import React from 'react';
import './tuner.list.component.css';
import { Websocket } from '../../websocket/websocket.service';

export class TunerList extends React.Component {
	constructor (props) {
		super(props);
		this.stationList = [];
		this.item = {};
		let a = this.state;
		console.warn('@!@@!@@@!!!', a);

	  	// this.ws = Websocket.getWS()
	  	// this.ws.onmessage = this.receive.bind(this); 
	}

	playStation () {
		console.warn('@@@ playStation');
	}


	// receive (msg) {
	// 	if (msg.data.cmd === 'resTunerListItems') {
	// 		console.log(msg.data.cmd);
			
	// 	}
	// }

	render() {
		return (
			<div className="list-container">
				<ul>
					<li className="list-item" onClick={this.playStation.bind(this.item)}>
						<span className="fav-ico-container">
							<span>LIST TUNER</span>
							<img src={ require('../../assets/media/favorite_icon.png') }/>
						</span>
						<span>{ this.item.name }</span>
					</li>
				</ul>
			</div>

		);
	}
}

// Angular/HMI-app/src/app/tuner/tuner-list/tuner-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

import { WebsocketWrapperService } from '../../services/websocket-wrapper.service';
import { TunerService } from '../../services/tuner.service';

@Component({
    selector: 'app-tuner-list',
    templateUrl: './tuner-list.component.html',
    styleUrls: ['./tuner-list.component.css']
})
export class TunerListComponent implements OnInit {

    constructor(private route: ActivatedRoute,
        private router: Router,
        private webSocketService: WebsocketWrapperService,
        private tunerService: TunerService) { }

    band;
    sub;

    ngOnInit() {
        this.getListItems();
    }

    getListItems() {
        console.warn('GET TUNER LIST ITEMS');
        this.webSocketService.send(JSON.stringify({ cmd: 'reqTunerListItems', band: this.band }));
    }

    playStation(station) {
        console.warn('PLAY STATION', station);
        this.webSocketService.send(JSON.stringify({ cmd: 'reqPlayStation', fraquence: station.fraquence }));
        this.router.navigate(['tuner']);
    }

}

<p>
  tuner-list works!
</p>
<div class="list-container">
	<ul>
		<li *ngFor="let item of listItems" class="list-item" (click)="playStation(item)">
			<span class="fav-ico-container">
				<img *ngIf="item.isFavorite" class="fav-ico" src="assets/media/favorite_icon.png">
			</span>
			<span>{{ item.name }}</span>
		</li>
	</ul>
</div>
